title: 
logo: /assets/img/Soumya.jpeg

description:
  <p align="center">
  <a href="pdf/resume.pdf">TODO</a> |
  <a href="https://www.linkedin.com/in/soumya-swaroop-gupta/">LinkedIn</a> |
  <a href="https://github.com/sswaroopgupta">GitHub</a>
  
  <br>   
  I have worked as a Developer,BA, QA. 
  
  Now I'm cross skilling myself to work on Data Science, AI and Machine learning related problems.
  <br>
  </p>

theme: jekyll-theme-minimal